### ISSUE TITLE
Text file busy - ./app (Errno::ETXTBSY)

### ISSUE THREAD

**Issue by fsdevblog** [jwoertink/guard-kemal#3]
Sorry for my bad english. I will try explain as i can...

Sometimes i have the error:
```
/home/fsdev/.rvm/gems/ruby-2.4.1/gems/guard-kemal-0.1.3/lib/guard/kemal/runner.rb:14:in `exec': Text file busy - ./app (Errno::ETXTBSY)
	from /home/fsdev/.rvm/gems/ruby-2.4.1/gems/guard-kemal-0.1.3/lib/guard/kemal/runner.rb:14:in `block in start!'
	from /home/fsdev/.rvm/gems/ruby-2.4.1/gems/guard-kemal-0.1.3/lib/guard/kemal/runner.rb:13:in `fork'
	from /home/fsdev/.rvm/gems/ruby-2.4.1/gems/guard-kemal-0.1.3/lib/guard/kemal/runner.rb:13:in `start!'
....
```
And after, i get another error:
```
[development] Kemal is ready to lead at http://0.0.0.0:3001
bind: Address already in use (Errno)
  from /usr/share/crystal/src/socket/tcp_server.cr:71:15 in 'initialize'
  from /usr/share/crystal/src/socket/tcp_server.cr:32:3 in 'initialize:reuse_port'
```
When i press `Ctrl+C` to exit from guard console, i check `netstat`, and I see, that kemal process still running.
```
$ netstat -ntlp | grep LISTEN
....
tcp        0      0 127.0.0.1:5432          0.0.0.0:*               LISTEN      -               
tcp        0      0 0.0.0.0:3001            0.0.0.0:*               LISTEN      7006/app        
tcp6       0      0 :::445                  :::*                    LISTEN      -               
...
```

**Comment by jwoertink** [comment]
Ah, yeah. Doing a `Sigint.trap` doesn't bubble down to crystal to tell kemal to stop. I will see if guard has something that we can send that to kemal. Thanks for reporting!
